local uv = require("luv")
local directory = assert(uv.fs_realpath(arg[0])):match("^(.*)/[^/]+$")
local pty = dofile(directory .. "/pty_runner.lua")
local interpreter, env = assert(uv.exepath()), pty.environment()
local function fails(argv, keys, timeout, message)
  local ok, err = pcall(pty.run, argv, env, keys, "", timeout)
  assert(not ok and tostring(err):find(message, 1, true), tostring(err))
  assert(not uv.loop_alive(), "PTY failure leaked event-loop handles")
end

local code, output = pty.run({ "/bin/stty", "-f", "/dev/tty", "size" }, env, {})
assert(code == 0 and output == "30 100\n", output)
code, output = pty.run({ interpreter, "-e", "io.write(io.read('*a')); os.exit(7)" }, env, {}, "raw\ninput\0bytes")
assert(code == 7 and output == "raw\ninput\0bytes", "PTY changed command status or stdin/stdout bytes")
fails({ interpreter, "-e", "os.exit(0)" }, { "unexpected" }, 3000, "exited early")
fails({ "pickr-nonexistent-pty-command" }, {}, 3000, "PTY wrapper failed")
fails({ interpreter, "-e", "require('luv').sleep(10000)" }, {}, 300, "PTY timed out")
code, output = pty.run({ interpreter, "-e", "io.write('recovered')" }, env, {})
assert(code == 0 and output == "recovered" and not uv.loop_alive())
print("Lua PTY runner: geometry, raw I/O, exit status, premature exit, launch failure, timeout cleanup and recovery pass")
